name: Compile LaTeX Resume

on:
  push:
    paths:
      - "**.tex" 
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xu-cheng/texlive-full:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile LaTeX to PDF
        run: pdflatex -interaction=nonstopmode -output-directory=. main.tex

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: output/resume.pdf

      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          keep_files: true
